base:

  origin:
    - sca
    - attacking
    - deep

  name: DeepStaticDiscrimination
  id: test3

  description: 'fit of the discriminative distribution of key given the static trace, using MLE'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: DeepStaticDiscriminator
  params:

    training_path: /data/output/DeepProfiler/test0
    checkpoint_file: epoch=14-step=5399.ckpt
    voltages:
    #  - '1.00'
    frequencies:
    #  - '48.000'
    key_values:
    #  - '00'
    #  - '01'
    #  - '02'
    #  - '03'
    #  - '04'
    #  - '05'
    #  - '06'
    #  - '07'
    plain_bounds: [300, 500]
    batch_size: 32

    num_workers: #4
    workers_type: #'threads'