base:

  origin:
    - sca
    - attacking
    - deep

  name: DeepDiscrimination0
  id: 0

  description: 'fit of the discriminative distribution of key given the trace, using MLE'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: DeepDiscriminator
  params:

    loader:
      name: FileConvention2
      params:
    
    voltages:
      - '1.00'
    frequencies:
      - '45.000'
    key_values:
      - '00'
      - '01'
      - '02'
      - '03'
      - '04'
      - '05'
      - '06'
      - '07'
    plain_bounds: [300, 500]

    training_path: /data/output/KeyClassifierTemp/2022-02-01_19-33-00
    checkpoint_file: epoch=30-step=3719.ckpt
    batch_size: 32

    num_workers: #4
    workers_type: #'threads'