base:

  origin:
    - sca
    - attacking
    - discriminator

  name: Discriminator0
  id: 0

  description: 'fit of the discriminative distribution of key given the trace, using MLE'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: KeyDiscriminator
  params:

    loader:
      name: FileConvention2
      params:

    #generator_path: C:\Users\rocca\Documents\Projects\SideChannelAttack\.output\Generator1\0
    generator_path: /data/output/Generator0/0
    plain_bounds: [300, 500]
