base:

  origin:
    - sca
    - preprocessing
    - window
    - lookup

  name: WindowLookup0
  id: 1

  description: 'creation of window lookup data'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: LookupCreation
  params:

    loader:
      name: FileConvention2
      params:
        slicer:
          name: Random
          params:
            window_size: 500
            num_windows: 1

          #name: Strided
          #params:
          #  window_size: 500
          #  stride: 10000

    voltages:
      - '1.00'
    frequencies:
      - '45.000'
      - '46.875'
      - '48.000'
      - '50.000'
      - '50.125'
      - '52.000'
      - '54.000'
      - '55.000'
      - '56.000'
    key_values:
      #- '00'
      #- '01'
    plain_bounds: [0, 300]

    size: 0.2

    partitioning:
      mapping:
        enabled: True
        bucket_size: 1000

      sets:
        - name: train
          size: 0.75
        - name: valid
          size: 0.15
        - name: test
          size: 0.1
