base:

  origin:
    - sca
    - profiling

  prompt:
    - window
    - classification
    - frequency

  name: Experiment3
  description: 'now splitting on traces in files'

# ---------------------------------------------------------------

determinism:

  seed: 314159
  seed_workers: True
  force: False

# ---------------------------------------------------------------

core:

  dataset:
    size: 0.1 # 0.001

    training:
      skip: False
      size: 0.8

    validation:
      size: 0.15

    test:
      skip: False

    chunks: 500

    params:
      loader:
        name: FileConvention1
        params:
          slicer:
            name: Random
            params:
              window_size: 1000
              num_windows: 1

      voltages:
        - '1.00'
      frequencies:
        - '45.000'
        - '46.875'
        - '48.000'
        - '50.000'
        - '52.000'
        - '54.000'
        - '55.000'
        - '56.000'
      key_values:

  model:
    checkpoint:

    name: Basic
    params:
      encoder:
        name: ResNet
        params:
          encoding_dim: 240
          base_filters: 16
          kernel_size: 10
          stride: 1
          groups: 1
          n_block: 15
          downsample_gap: 2
          increasefilter_gap: 4
          # use_bn: True
          # use_ido: True
          ido_val: 0.3
          # use_fdo: True
          fdo_val: 0.7

# ---------------------------------------------------------------

learning:

  loss:
    name: CrossEntropyLoss
    params:

  early_stopping:
    monitor: valid/loss
    patience: 5
    mode: min

  optimizer:
    name: SGD
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay: 1e-4

  scheduler:
    name: StepLR
    params:
      step_size: 2
      gamma: 0.9

  data_loader:
    batch_size: 64
    shuffle: True
    num_workers: 2
    pin_memory: True

  trainer:
    gpus: 1
    max_epochs: 60
    check_val_every_n_epoch: 1
    log_every_n_steps: 100
    limit_train_batches: 0.244 # 0.035
    limit_val_batches: 0.244 # 0.035

  loggables:
    - name: Accuracy
      params:

    - name: ConfusionMatrix
      params:
        normalize: 'true'

# ---------------------------------------------------------------

logging:

  tensorboard:
    enable: True

  neptune:
    enable: True
    
    log_model_checkpoints: False
    tags:
      - resnet
      - window-1000
      - random-slice
      - split-on-chunks

    # source_files:
    # - '*.py'
    # - '*.sh'
