base:

  origin:
    - sca
    - profiling

  prompt:
    - window
    - classification
    - frequency

  name: Experiment1
  description: 'on gpu with entire dataset'

# ---------------------------------------------------------------

determinism:

  seed: 314159
  seed_workers: True
  force: False

# ---------------------------------------------------------------

core:

  dataset:
    num_samples: 0.001

    params:
      loader:
        name: FileConvention1
        params:
          slicer:
            name: Strided
            params:
              window_size: 5000
              stride: 200

      voltages:
        - '1.00'
      frequencies:
        - '45.000'
        - '46.875'
        - '48.000'
        - '50.000'
        - '52.000'
        - '54.000'
        - '55.000'
        - '56.000'
      key_values:
      num_traces: 500

  model:
    checkpoint:

    name: Basic
    params:
      encoder:
        name: ResNet
        params:
          encoding_dim: 160
          base_filters: 16
          kernel_size: 5
          stride: 1
          groups: 1
          n_block: 7
          downsample_gap: 2
          increasefilter_gap: 3
          use_bn: True
          use_do: True

# ---------------------------------------------------------------

learning:

  skip:
    training:
    test: True

  split:
    validation: 0.15
    test: 0.05

  early_stopping:
    monitor: valid/loss
    patience: 10
    mode: min

  loss:
    name: CrossEntropyLoss
    params:

  optimizer:
    name: SGD
    params:
      lr: 0.02
      momentum: 0.9
      weight_decay: 1e-4

  scheduler:
    name: StepLR
    params:
      step_size: 1
      gamma: 0.9

  data_loader:
    batch_size: 64
    shuffle: True
    num_workers: 4
    pin_memory: True

  trainer:
    gpus: 1
    max_epochs: 100
    check_val_every_n_epoch: 1
    log_every_n_steps: 100
    limit_train_batches: 0.035
    limit_val_batches: 0.035

  loggables:
    - name: Accuracy
      params:

    - name: ConfusionMatrix
      params:
        normalize: 'true'

# ---------------------------------------------------------------

logging:

  tensorboard:
    enable: True

  neptune:
    enable: True
    
    log_model_checkpoints: False
    tags:
      - unstable
      - resnet

    # source_files:
    # - '*.py'
    # - '*.sh'