base:

  origin:
    - sca
    - profiling

  prompt:
    - window
    - classification
    - frequency

  name: Experiment6
  description: 'classification of two critical frequencies'

# ---------------------------------------------------------------

determinism:

  seed: 314159
  seed_workers: True
  force: False

# ---------------------------------------------------------------

core:

  dataset:
    size: 0.2 # 0.1

    training:
      skip: False
      size: 0.8

    validation:
      size: 0.15

    test:
      skip: False

    chunks: 500

    params:
      loader:
        name: FileConvention1
        params:
          slicer:
            name: Random
            params:
              window_size: 1000
              num_windows: 1

      voltages:
        - '1.00'
      frequencies:
        #- '45.000'
        - '46.875'
        #- '48.000'
        - '50.000'
        #- '52.000'
        #- '54.000'
        #- '55.000'
        #- '56.000'
      key_values:

      channels_first: True

  model:
    checkpoint:

    name: Basic
    params:
      encoder:
        name: ResNet
        params:
          encoding_size: 40
          base_filters: 32
          kernel_size: 20
          stride: 1
          groups: 1
          n_block: 20
          downsample_gap: 2
          increasefilter_gap: 4
          use_batch_norm: True
          use_inner_do: True
          inner_do_val: 0.5
          use_final_do: True
          final_do_val: 0.5

        #name: LSTM1
        #params:
        #  batch_first: True
        #  encoding_size: 80
        #  use_final_do: False
        #  final_do_val: 0.3
        #  hidden_size: 240
        #  num_layers: 1
        #  dropout: 0

        #name: Transformer
        #params:
        #  batch_first: True
        #  encoding_size: 160
        #  use_final_do: True
        #  final_do_val: 0.2
        #  dim_feedforward: 500
        #  nhead: 1
        #  dropout: 0.1

# ---------------------------------------------------------------

learning:

  loss:
    name: CrossEntropyLoss
    params:
      #weight:
      #  - 1.0
      #  - 3.0
      #  - 1.0
      #  - 3.0
      #  - 1.0
      #  - 1.0
      #  - 1.0
      #  - 1.0

  early_stopping:
    monitor: valid/loss
    patience: 10
    mode: min

  optimizer:
    name: SGD
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay: 1e-4
    #name: Adam
    #params:


  scheduler:
    name: StepLR
    params:
      step_size: 2
      gamma: 0.9

  data_loader:
    batch_size: 64
    shuffle: True
    num_workers: 2
    pin_memory: True

  trainer:
    gpus: 1
    max_epochs: 70
    check_val_every_n_epoch: 1
    log_every_n_steps: 100
    limit_train_batches: 0.244
    limit_val_batches: 0.244
    track_grad_norm: 2

  loggables:
    - name: Accuracy
      params:

    - name: ConfusionMatrix
      params:
        normalize: 'true'

# ---------------------------------------------------------------

logging:

  tensorboard:
    enable: True

  neptune:
    enable: True
    
    log_model_checkpoints: False
    tags:
      - resnet
      - window-1000
      - random-slice
      - split-on-chunks
      - critical frequencies
      - size-2x

    # source_files:
    # - '*.py'
    # - '*.sh'
