base:

  origin:
    - sca
    - attacking
    - deep

  name: DeepDynamicDiscrimination
  id: good0

  description: 'fit of the discriminative distribution of key given the dynamic trace, using MLE'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: DeepDynamicDiscriminator
  params:

    dynamic_path: /data/output/DynamicSegmentation/prod0
    training_path: /data/output/DeepDynamicProfiler/2022-02-21_08-52-38
    checkpoint_file: epoch=8-step=809.ckpt
    key_values: 150
    #  - '00'
    #  - '01'
    #  - '02'
    #  - '03'
    #  - '04'
    #  - '05'
    #  - '06'
    #  - '07'
    plain_bounds: [300, 500]
    batch_size: 64

    num_workers: 8
    workers_type: 'processes'