base:

  origin:
    - sca
    - attacking
    - classic
    - aligned

  name: AlignedStaticDiscrimination
  id: temp0

  description: 'fit of the discriminative distribution of key given the aligned static traces, using MLE'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: AlignedStaticDiscriminator
  params:

    generator_path: /data/output/TraceGenerator/test0
    voltages:
      - '1.00'
    frequencies:
      #- '45.000'
      #- '46.875'
      - '48.000'
      #- '50.000'
      #- '50.125'
      #- '52.000'
      - '54.000'
      #- '55.000'
      #- '56.000'
    plain_bounds: [300, 500]
    target_volt: '1.00'
    target_freq: '52.000'
    interp_kind: quadratic

    num_workers: #4
    workers_type: #threads
