base:

  origin:
  - sca

  prompt:
  - window
  - classification
  - frequency

  name: 'Test'
  description: 'this is a test'

# ---------------------------------------------------------------

determinism:

  seed: 314159
  seed_workers: True
  force: False

# ---------------------------------------------------------------

core:

  dataset:
    num_samples: 1000

    params:
      loader:
        name: FileConvention1
        params:
          slicer:
            name: Strided
            params:
              window_size: 1000
              stride: 50

      voltages:
      - '1.00'
      frequencies:
      - '48.000'
      - '52.000'
      key_values:
      - '32'
      - 'a3'
      num_traces: 500

  model:
    checkpoint:

    name: Basic
    params:
      encoder:
        name: ResNet
        params:
          encoding_dim: 100
          base_filters: 10
          kernel_size: 4
          stride: 1
          groups: 1
          n_block: 10
          downsample_gap: 2
          increasefilter_gap: 4
          use_bn: True
          use_do: True

# ---------------------------------------------------------------

learning:

  skip:
    training:
    test: False

  split:
    validation: 0.1579
    test: 0.05

  data_loader:
    batch_size: 20
    num_workers: 8
    shuffle: True

  early_stopping:
    monitor: 'valid/accuracy'
    patience: 5
    mode: 'max'

  trainer:
    gpus: 0
    max_epochs: 20
    check_val_every_n_epoch: 1

  loss:
    name: CrossEntropyLoss
    params:

  optimizer:
    name: SGD
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay: 1e-4

  scheduler:
    name: StepLR
    params:
      step_size: 2
      gamma: 0.9

# ---------------------------------------------------------------

logging:

  tensorboard:
    enable: True

  neptune:
    enable: False
    
    log_model_checkpoints: False
    # source_files:
    # - '*.py'
    # - '*.sh'