base:

  prompt:
  - window
  - classification
  - frequency

  name: Test

  skip:
    training:
    testing:

# ---------------------------------------------------------------

determinism:

  seed: 314159
  seed_workers: True
  force_determinism: False

# ---------------------------------------------------------------

logging:

  tensorboard:
    enable: True

  neptune:
    enable: False
    
    offline_mode: False
    project_name:
    upload_source_files:
    - '*.py'
    - '*.c'
    - '*.yaml'

# ---------------------------------------------------------------

core:

  dataset:
    params:
      slicer:
        name: StridedSlicer
        params:
          window_size: 1000
          stride: 50

      voltages:
      - '1.00'
      frequencies:
      - '52.000'
      key_values:
      - '32'
      - 'a3'
      num_traces: 500

  model:
    name: A
    params:
      encoder:
        name: ResNet
        params:
          base_filters: 10
          kernel_size: 4
          stride: 1
          groups: 1
          n_block: 10
          downsample_gap: 2
          increasefilter_gap: 4
          use_bn: True
          use_do: True

    checkpoint:

# ---------------------------------------------------------------

learning:

  validation_split: 0.1

  data_loader:
    batch_size: 32
    num_workers: 8
    shuffle: True

  early_stopping:
    monitor: 'validation/acc'
    patience: 5
    mode: 'max'

  trainer:
    gpus: 0
    max_epochs: 20
    check_val_every_n_epoch: 1

  loss:
    name: CrossEntropyLoss
    params:

  optimizer:
    name: SGD
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay: 1e-4

  scheduler:
    name: StepLR
    params:
      step_size: 2
      gamma: 0.9