base:

  origin:
    - sca
    - attacking
    - discriminator
    - basic

  name: BasicDiscrimination0
  id: 1

  description: 'fit of the discriminative distribution of key given the trace, using MLE'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: BasicDiscriminator
  params:

    loader:
      name: FileConvention2
      params:

    #generator_path: C:\Users\rocca\Documents\Projects\SideChannelAttack\.output\Generator1\0
    generator_path: /data/output/Generator0/0
    voltages:
      - '1.00'
    frequencies:
      #- '45.000'
      #- '50.000'
    plain_bounds: [300, 500]
