base:

  origin:
    - sca
    - attacking
    - discriminator
    - aligned

  name: StaticDiscrimination0
  id: 1

  description: 'fit of the discriminative distribution of key given the aligned static trace, using MLE'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: StaticDiscriminator
  params:

    loader:
      name: FileConvention2
      params:

    #generator_path: C:\Users\rocca\Documents\Projects\SideChannelAttack\.output\Generator1\0
    generator_path: /data/output/Generator0/0
    voltages:
      - '1.00'
    frequencies:
      - '46.875'
      - '48.000'
      - '50.000'
      - '50.125'
      - '52.000'
      - '54.000'
      - '55.000'
      - '56.000'
    plain_bounds: [300, 500]

    target_volt: '1.00'
    target_freq: '45.000'
    interp_kind:
