base:

  origin:
    - sca
    - profiling
    - classic
    - aligned
    - segmentation
    - dynamic

  name: A-DynamicSegmentation
  id: 0

  description: 'frequency segmentation of static traces using a frequency classifier'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: DynamicSegmentation
  params:

    loader:
      name: FileConvention2
      params:
        trace_len: 100000
    
    #training_path: /data/output/FrequencyAlignerTemp/2022-02-01_22-33-49
    #checkpoint_file: epoch=8-step=2915.ckpt
    training_path: ./.output/A-FrequencyAligner/0
    checkpoint_file: epoch=1-step=25.ckpt
    key_values:
      - '00'
      - '01'
      #- '02'
      #- '03'
      #- '04'
      #- '05'
      #- '06'
      #- '07'
    plain_bounds: [495, 500]
    batch_size: 1
    interp_kind: quadratic
    mu: 15000
    sigma: 4000
    log_assembler: True
    log_segmentation: True
    log_localization: #True
    min_window_len: 3000
    max_window_len: 30000

    num_workers: #4
    workers_type: #'threads'