base:

  origin:
    - sca
    - profiling
    - classic
    - aligned
    - segmentation
    - static

  name: A-StaticSegmentation
  id: 0

  description: 'frequency segmentation of static traces using a frequency classifier, also creates synamic trace dataset lookup files'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: StaticSegmentation
  params:

    loader:
      name: FileConvention2
      params:
        trace_len: 100000
    
    #training_path: /data/output/A-FrequencyAligner/0
    #checkpoint_file: epoch=3-step=1151.ckpt
    training_path: ./.output/A-FrequencyAligner/0
    checkpoint_file: epoch=1-step=25.ckpt
    key_values:
      - '00'
      - '01'
      #- '02'
      #- '03'
      #- '04'
      #- '05'
      #- '06'
      #- '07'
    plain_bounds: [499, 500]
    batch_size: 1
    interp_kind: quadratic
    log_segmentation: True
    log_localization: #True

    num_workers: #4
    workers_type: #'threads'