base:

  origin:
    - sca
    - profiling
    - classic
    - aligned
    - segmentation
    - static

  name: StaticSegmentation0
  id: test

  description: 'frequency segmentation of static traces using a frequency classifier'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: StaticSegmentation
  params:

    loader:
      name: FileConvention2
      params:
    
    voltages:
      - '1.00'
    frequencies:
      - '45.000'
      - '54.000'
    key_values:
      - '00'
      - '01'
      #- '02'
      #- '03'
      #- '04'
      #- '05'
      #- '06'
      #- '07'
    plain_bounds: [480, 500]

    training_path: /data/output/FrequencyAlignerTemp/2022-02-01_22-33-49
    checkpoint_file: epoch=8-step=2915.ckpt
    batch_size: 1
    interp_kind: quadratic
    trace_len: 100000
    log_segmentation: #True
    log_localization: #True

    num_workers: #4
    workers_type: #'threads'