base:

  origin:
    - sca
    - attacking
    - classic
    - aligned

  name: AlignedDynamicDiscrimination
  id: prod0

  description: 'fit of the discriminative distribution of key given the aligned dynamic traces, using MLE'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: AlignedDynamicDiscriminator
  params:

    dynamic_path: /data/output/DynamicSegmentation/prod0
    generator_path: /data/output/TraceGenerator/temp0
    localization_path: /data/output/DynamicSegmentation/prod0/localization
    plain_bounds: [300, 500]
    target_freq: '52.000'
    skip_size_lim: 100
    interp_kind: quadratic

    num_workers: #4
    workers_type: #threads
