base:

  origin:
    - sca
    - attacking
    - classic
    - aligned

  name: AlignedDynamicDiscrimination
  id: test3

  description: 'fit of the discriminative distribution of key given the aligned dynamic traces, using MLE'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: AlignedDynamicDiscriminator
  params:

    dynamic_path: /data/output/DynamicSegmentation/test2
    generator_path: /data/output/TraceGenerator/test0
    localization_path: /data/output/DynamicSegmentation/test2/localization
    plain_bounds: [300, 500]
    target_freq: '48.000'
    interp_kind: quadratic

    num_workers: #4
    workers_type: #threads
