base:

  origin:
    - sca
    - attacking
    - classic
    - aligned

  name: A-AlignedDynamicDiscrimination
  id: 0

  description: 'fit of the discriminative distribution of key given the aligned dynamic traces, using MLE'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: AlignedDynamicDiscriminator
  params:

    dynamic_path: # path to segm/assembler
    generator_path: /data/output/Generator0/0
    localization_path: # path to segm/localization
    plain_bounds: [300, 500]
    target_freq: '52.000'
    interp_kind: #linear

    num_workers: #4
    workers_type: #threads
