base:

  origin:
    - sca
    - attacking
    - classic
    - basic

  name: A-BasicDiscrimination
  id: 0

  description: 'fit of the discriminative distribution of key given the trace, using MLE'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: BasicDiscriminator
  params:
  
    generator_path: /data/output/Generator0/0
    voltages:
      - '1.00'
    frequencies:
      #- '45.000'
      #- '50.000'
    plain_bounds: [300, 500]

    num_workers: #4
    workers_type: #'threads'