base:

  origin:
    - sca
    - attacking
    - classic
    - basic

  name: BasicDiscrimination
  id: test1

  description: 'fit of the discriminative distribution of key given the trace, using MLE'

# ---------------------------------------------------------------

determinism:

  seed: 314159

# ---------------------------------------------------------------

core:

  name: BasicDiscriminator
  params:
  
    generator_path: /data/output/TraceGenerator/test0
    voltages:
    #  - '1.00'
    frequencies:
    #  - '48.000'
      - '52.000'
      - '54.000'
    plain_bounds: [300, 500]

    num_workers: #4
    workers_type: #'threads'